const adTypes = {
  FETCH_ADS_START: "FETCH_ADS_START",
  FETCH_ADS_SUCCESS: "FETCH_ADS_SUCCESS",
  ADD_AD_START: "ADD_AD_START",
  LIKE_AD_START: "LIKE_AD_START",
  COMMENT_AD_START: "COMMENT_AD_START",
  DELETE_AD_START: "DELETE_AD_START_AD_START",
  SORT_ADS_BY_LIKE_START: "SORT_ADS_BY_LIKE_START",
  AD_ERROR: "AD_ERROR",
};

export default adTypes;
